### ISSUE TITLE
Addition of **kwargs for mode

### ISSUE THREAD

**Issue by scsanty** [xor2k/npy_append_array#4]
Addition of an option to recreate the file.

Say a file exists with the same name, in which we want to save new numpy array (of different shape or data type). and hence we want to initiate an empty file like mode='wb' and then go 'ab' on the same file.

**Comment by xor2k** [comment]
There is a new option `delete_if_exists`: if the file existed before, it will be deleted. Does this solve the issue?

**Comment by scsanty** [comment]
Thanks, that makes sense.
