### ISSUE TITLE
Citation for code

### ISSUE THREAD

**Issue by oneil571** [xor2k/npy_append_array#9]
Hello! I used npy-append-array in a scan processing research project that is going to be published soon. The code worked beautifully; it gave a ~5* speedup when simultaneously appending many large arrays in-disk as opposed to one by one in-memory. Thus, I would like to cite your code for the paper! Can your please provide your preferred citation (or at least Michael's last name)? Thanks much.

**Comment by xor2k** [comment]
Hi, thanks a lot for the request, I've created a `citation.cff` with a valid doi etc. My full name is also in that file.

Always happy to hear my work is useful ;)

Can I close this issue?

Best, Michael

**Comment by oneil571** [comment]
Hi Michael,

Thanks so much! Yes, please close the issue now.

All the best,
Riley
